/*
 * This source file was generated by the Gradle 'init' task
 */
package org.zirbes.iceberg

object App {

    @JvmStatic
    fun main(args: Array<String>) {
        println("🚀 Launching!")
        Playground().run()
    }

}
