services:
  minio:
    # minioadmin, minioadmin
    image: hub.docker.target.com/minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9006:9006"
      - "9007:9007"
    restart: always
    environment:
      MINIO_ROOT_USER: iceberg
      MINIO_ROOT_PASSWORD: playground
    entrypoint: [ "minio", "server", "/home/minio", "--compat", "--address", ":9006", "--console-address", ":9007" ]
