/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version libs.versions.kotlin.core
    alias(libs.plugins.spotless)
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.bundles.iceberg)
    implementation(libs.minio.client)

    testImplementation(libs.slf4j.simple)
    testImplementation(libs.bundles.testing)

}

//testing {
//    suites {
//        // Configure the built-in test suite
//        val test by getting(JvmTestSuite::class) {
//            // Use Kotlin Test test framework
//            useJUnit("2.0.21")
//        }
//    }
//}

val jvmTargetVersion: String by project

tasks {
    java { toolchain { languageVersion = JavaLanguageVersion.of(17) } }

    withType<Test> {
        systemProperty("kotest.framework.classpath.scanning.config.disable","true")
        systemProperty("kotest.framework.classpath.scanning.autoscan.disable","true")
        useJUnitPlatform()
        this.testLogging { this.showStandardStreams = true }
        jvmArgs("--add-opens", "java.base/java.util=ALL-UNNAMED")
    }
}


application {
    mainClass = "org.zirbes.iceberg.App"
}
